# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Rajesh Nakarja
title: Chief Engineer of Wearable Hardware
email: raj@siliconwitchery.com
website: https://github.com/siliconwitch

# Social links
github_username:  siliconwitch
linkedin_username: rajesh-nakarja-embedded
twitter_username: siliconwitch
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.gif
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Raj, and I'm Chief Engineer of Wearable Hardware at Silicon Witchery. I have previously worked for companies big and small, doing a variety of engineering task such as designing robotics, automotive software and carrying out RF compliance.

  I am most skilled in: <mark>Hardware</mark>, <mark>Firmware</mark> and general <mark>IoT Hacking</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# education_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in electronics, some of my other hobbies are:
   - Learning, as well as teaching about Space & Science
   - Classic car & bike restoration
   - <a href="https://en.wikipedia.org/wiki/Renaissance_fair" target="_blank">Renaissance fairs</a>
   - <a href="https://www.instagram.com/siliconwitch.pole/" target="_blank">Athletic pole dancing</a>

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
