# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Rajesh Nakarja
title: Chief Engineer of Wearable Systems
email: raj@siliconwitchery.com
website: https://github.com/siliconwitch

# Social links
twitter_username: siliconwitch
github_username:  siliconwitch
linkedin_username: rajesh-nakarja-embedded
# facebook_username: rajeshnakarja
# dribbble_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Raj, and I'm Chief Engineer of Wearable Systems at Silicon Witchery. I've previously worked for companies big and small, focusing largely on <mark>consumer wearables</mark>, and <mark>IoT products</mark>.

  Over the years I've been involved in end-to-end product development. From drawing specifications with customers to the factory floor ensuring correct assembly. I've also worked closely with technology partners and EMC test facilities to ensure our products have been fully verified before launch.

  I'm an embedded systems engineer that loves to build hardware and write code. But my experience in end-to-end product development gives me the edge to see the bigger picture. I always strive to build the best for the business and value good communication to keep things running smoothly.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# education_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in electronics, some of my other hobbies include:
   - STEM outreach and volunteering.
   - Plot acting at live roleplay events, including the UK's largest, attracting over 1800 visitors per year.
   - Folk singing at maritime and renaissance fairs.
   - Athletic pole dancing.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
